all:	
	cc -lpthread dataSharing.c -o 	dataSharing
	cc -lpthread file_thread.c  -o	file_thread
	cc -lpthread first_thread.c -o	first_thread
	cc -lpthread jointhread.c -o	jointhread
	cc -lpthread parameter_to_thread.c -o	parameter_to_thread
	cc -lpthread prime_thread.c -o	prime_thread
	cc -lpthread pthread_self.c -o	pthread_self
	cc -lpthread simplethread.c -o	simplethread
	cc -lpthread thread_exit.c -o	thread_exit
	cc -lpthread thread_file.c -o	thread_file
	cc -lpthread thread_fork.c -o	thread_fork
	cc -lpthread threadsAndFork.c	-o threadsAndFork

clean : 	
	rm dataSharing
	rm file_thread
	rm first_thread
	rm jointhread
	rm parameter_to_thread
	rm prime_thread
	rm pthread_self
	rm simplethread
	rm thread_exit
	rm thread_file
	rm thread_fork
	rm threadsAndFork
