#

all:	shmcreate shmszget shmattch shmwrite shmread shmdel shmstat shmset shmexpl 

shmcreate:	shmcreate.c
	gcc -Wall -o shmcreate shmcreate.c

shmszget:	shmszget.c
	gcc -Wall -o shmszget shmszget.c

shmattch:	shmattch.c
	gcc -Wall -o shmattch shmattch.c

shmwrite:	shmwrite.c
	gcc -Wall -o shmwrite shmwrite.c

shmread:	shmread.c
	gcc -Wall -o shmread shmread.c

shmdel:	shmdel.c
	gcc -Wall -o shmdel shmdel.c

shmstat:	shmstat.c
	gcc -Wall -o shmstat shmstat.c

shmset:	shmset.c
	gcc -Wall -o shmset shmset.c

shmexpl:	shmexpl.c
	gcc -Wall -o shmexpl shmexpl.c

clean:
	rm -rf shmcreate shmszget shmattch shmwrite shmread shmdel shmstat shmset shmexpl


