#TARGET=Prog 
OFLAG=-o
CFLAG=-c
CC=gcc
#ALL=$(TARGET)

#.PHONY:prog

proge: prog.c  add.o mean.o mul.o sub.o

#add.o: add.c
#mean.o: mean.c
#mul.o: mul.c
#sub.o: sub.c

.PHONY:run

run :
	ls -l
	date
clean:
	@rm -f prog
	@rm -f add.o
	@rm -f mean.o
	@rm -f mul.o
	@rm -f sub.o

