target1=$(SRC_DIR)
target2:=$(SRC_DIR)

SRC_DIR=/home/karanth

target3=$(SRC_DIR)
target4:=$(SRC_DIR)

SRC_DIR=/home/karanth/dummy

run:
	@echo "target1 is :" $(target1)
	@echo "target2 is :"$(target2)
	@echo "target3 is :"$(target3)
	@echo "target4 is :"$(target4)
